name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.2"
    - name: Install Dependencies
      run: |
        cd project
        python -m pip install --upgrade pip
        pip install -r requirements1.txt
    - name: Run Tests
      run: |
        python manage.py test
